### ISSUE TITLE
Afbeeldingen missen alt-tags

### ISSUE THREAD

**Issue by ghost** [IvarSchuyt/the-client-case#3]
Op verschillende plekken in je code missen de alt-tags. Dat is zielig voor de blinde mensen 😕

**Comment by IvarSchuyt** [comment]
dove bedoel je

**Comment by ghost** [comment]
![AHI_43545239383534363430](https://user-images.githubusercontent.com/55235748/194515801-83193df9-dc8f-4f1e-b02f-31cfcc73cba2.jpeg)
