### ISSUE TITLE
<div> wordt niet afgesloten.

### ISSUE THREAD

**Issue by ghost** [IvarSchuyt/the-client-case#5]
https://github.com/IvarSchuyt/the-client-case/blob/ced8f3f5aba56c35be86b85959bcd720ab427586/index.html#L20-L37

De reden dat Prettier hoofdpijn kreeg, was waarschijnlijk dat er <div> niet goed afgesloten wordt.

**Comment by IvarSchuyt** [comment]
HIJ DOET HET WEER
![group-senior-people-having-birthday-party-seniors-birthday-party-102169527](https://user-images.githubusercontent.com/112855849/194524319-71eec7ca-8e2b-44d3-99c9-bbf0ee5149c5.jpg)
