### ISSUE TITLE
Verkeerde img naam

### ISSUE THREAD

**Issue by rosahoffer** [IvarSchuyt/the-client-case#8]
https://github.com/IvarSchuyt/the-client-case/blob/ced8f3f5aba56c35be86b85959bcd720ab427586/index.html#L18

Hi Ivar,

Het is beter om geen spatie te gebruiken in je IMG naam. Gebruik bijvoorbeeld een -

**Comment by IvarSchuyt** [comment]
shitttttttt thanks
